tabs:
- id: launcher
  name: Launcher
  categories:
  - id: env_tools
    name: Environment & Scaffolding
    items:
    - ai-env
    - ai-project
    - py-project
    - venv-create
  - id: project_automation
    name: Project Automation
    items:
    - git-init
    - new-proj
    - backup-project
  - id: ai_ops
    name: AI & Ollama Ops
    items:
    - ai-services
  - id: search_nav
    name: Search & Navigation
    items:
    - ff
  - id: monitors
    name: Monitors & Alerts
    items:
    - nvidia
    - nudge
  - id: productivity
    name: Productivity
    items:
    - timer
  - id: dangerous
    name: Dangerous
    items:
    - delete-workflows
    - ghauth
  layout:
    style: grid
    columns: 3
- id: details
  name: Details
  categories: []
  template: tool-detail
- id: maintenance
  name: Maintenance
  categories: []
  locked: true
metadata:
  version: 1
  last_updated_by: codex
  notes: 'Tabs beyond the launcher are rendered dynamically. Maintenance tools

    update this file when categories or ordering changes.

    '
