id: llm-tester
name: LLM Tester Enhanced
synopsis: Advanced LLM testing and parameter optimization platform with visualization.
command:
- bash
- ./run.sh
cwd: /home/herb/Desktop/MasterMenu/apps/llm-tester
env: {}
icon: icon.svg
category: Good To Go
notes: 'Relocatable LLM-Tester Enhanced v2.0 with comprehensive parameter optimization lab.

  Features include: model library, test suites, parameter presets, real-time monitoring,
  exhaustive parameter optimization, multidimensional visualization, and persistent data storage.

  Supports device relocation through symlinks and maintains data persistence across sessions.
  Automatically detects and links to existing desktop data for seamless migration.'
venv:
  path: .venv
  auto_create: true
tags:
- llm
- testing
- optimization
- visualization
- research
- cli
