id: finder
name: Finder Utility
synopsis: Launch the bundled Finder logical file search tool.
command:
- bash
- ./run.sh
cwd: .
env: {}
icon: icon.png
category: unassigned
notes: |
  Ships with the Finder desktop search application directly inside MasterMenu.
  The tool exposes logical phrase searches, validation helpers, and the
  educational test suites without depending on the old Desktop checkout.
  Optional virtualenv support mirrors other MasterMenu tools (`apps/finder/.venv`).
venv:
  path: .venv
  auto_create: false
tags:
- search
- utility
- cli
