id: pikapeek
name: PikaPeek Backup Explorer
synopsis: Launch the PikaPeek Borg backup explorer.
command:
- bash
- ./run.sh
cwd: .
env: {}
icon: icon.png
category: unassigned
notes: |
  Launches the bundled Simple Pika backup explorer. Set `PIKAPEEK_REPO_PATH`
  or `PIKAPEEK_REPO_ROOT` so the tool can find your Borg archives. Recovery
  copies default to the MasterMenu workdir but can be overridden with
  `PIKAPEEK_RECOVERY_PATH`.
venv:
  path: .venv
  auto_create: false
tags:
- backup
- borg
- cli
